<?php 

$DATA = [];

$DATA[] = [
    'code' => 'AABBCC100',
    'petName' => 'Alarick',
    'petImage' => 'https://bytetag-profile-pictures.s3.amazonaws.com/abc45285-ce60-42e1-a693-7d82f77e5c35.png?pfpVersion=Jf21',
    'petBreed' => 'Husky',
    'petBio' => 'A friendly Husky bog.',
    'gender' => 'Boy',
    'age' => '9',
    'weight' => '15',
    'dadName' => 'Alarick Owner',
    'dadContact' => '+490123456789',
    'dadLocation' => 'https://www.google.com/maps/@50.9982818,10.6353859,12.6z?entry=ttu',
    'dadAddress' => [
        'dadAddressLine1' => 'EE',
        'dadAddressLine2' => '',
        'dadAddressLine3' => '',
        'dadAddressLine4' => 'Päevalille tn',
        'dadAddressLine5' => '13517 Tallinn',
        'dadAddressLine6' => '',
        'dadAddressLine7' => '',
    ],
    'behavior' => [
        'goodWithKids' => 'Yes',
        'goodWithDogs' => 'Yes',
        'goodWithcats' => 'No',
    ],
    'health' => [
        'allergies'         => 'Yes',
        'medicine'          => 'Yes',
        'neutered_spayed'   => 'No',
    ],
    'provider' => [
        'vet_name'          => 'Not disclosed',
        'vet_phone'         => 'Not disclosed',
        'vet_license_id'    => '123456',
        'vet_microchip'     => '123567',
        'rabies_id'         => 'Not disclosed',
    ],
];

$DATA[] = [
    'code' => 'AABBCC101',
    'petName' => 'Hugo',
    'petImage' => 'https://www.thesprucepets.com/thmb/hxWjs7evF2hP1Fb1c1HAvRi_Rw0=/2765x0/filters:no_upscale():strip_icc()/chinese-dog-breeds-4797219-hero-2a1e9c5ed2c54d00aef75b05c5db399c.jpg',
    'petBreed' => 'Husky',
    'petBio' => 'A friendly Husky girl.',
    'gender' => 'Girl',
    'age' => '5',
    'weight' => '21',
    'dadName' => 'Hugo Owner',
    'dadContact' => '+490123456789',
    'dadLocation' => 'https://www.google.com/maps/search/Pharmacies/@50.9704436,10.7269859,14.6z?entry=ttu',
    'dadAddress' => [
        'dadAddressLine1' => 'EE',
        'dadAddressLine2' => '',
        'dadAddressLine3' => '',
        'dadAddressLine4' => 'Päevalille tn',
        'dadAddressLine5' => '13517 Tallinn',
        'dadAddressLine6' => '',
        'dadAddressLine7' => '',
    ],
    'behavior' => [
        'goodWithKids' => 'Yes',
        'goodWithDogs' => 'Yes',
        'goodWithcats' => 'No',
    ],
    'health' => [
        'allergies'         => 'Yes',
        'medicine'          => 'Yes',
        'neutered_spayed'   => 'No',
    ],
    'provider' => [
        'vet_name'          => 'Not disclosed',
        'vet_phone'         => 'Not disclosed',
        'vet_license_id'    => '123456',
        'vet_microchip'     => '123567',
        'rabies_id'         => 'Not disclosed',
    ],
];

$DATA[] = [
    'code' => 'AABBCC102',
    'petName' => 'Norbert',
    'petImage' => 'https://images.newscientist.com/wp-content/uploads/2021/07/20164548/gettyimages-171117216_web.jpg',
    'petBreed' => 'Husky',
    'petBio' => 'A friendly Husky girl.',
    'gender' => 'Boy',
    'age' => '6',
    'weight' => '18',
    'dadName' => 'Norbert Owner',
    'dadContact' => '+490123456789',
    'dadLocation' => 'https://www.google.com/maps/search/Pharmacies/@50.946936,10.7051881,14z?entry=ttu',
    'dadAddress' => [
        'dadAddressLine1' => 'EE',
        'dadAddressLine2' => '',
        'dadAddressLine3' => '',
        'dadAddressLine4' => 'Päevalille tn',
        'dadAddressLine5' => '13517 Tallinn',
        'dadAddressLine6' => '',
        'dadAddressLine7' => '',
    ],
    'behavior' => [
        'goodWithKids' => 'Yes',
        'goodWithDogs' => 'Yes',
        'goodWithcats' => 'No',
    ],
    'health' => [
        'allergies'         => 'Yes',
        'medicine'          => 'Yes',
        'neutered_spayed'   => 'No',
    ],
    'provider' => [
        'vet_name'          => 'Not disclosed',
        'vet_phone'         => 'Not disclosed',
        'vet_license_id'    => '123456',
        'vet_microchip'     => '123567',
        'rabies_id'         => 'Not disclosed',
    ],
];

$DATA[] = [
    'code' => 'AABBCC103',
    'petName' => 'Rune',
    'petImage' => 'https://i.pinimg.com/originals/ca/36/53/ca3653e8beff43d17ff991a804a03abb.jpg',
    'petBreed' => 'Husky',
    'petBio' => 'A friendly Husky girl.',
    'gender' => 'Girl',
    'age' => '8',
    'weight' => '14',
    'dadName' => 'Rune Onwer',
    'dadContact' => '+490123456789',
    'dadLocation' => 'https://www.google.com/maps/search/Pharmacies/@50.946936,10.7051881,14z?entry=ttu',
    'dadAddress' => [
        'dadAddressLine1' => 'EE',
        'dadAddressLine2' => '',
        'dadAddressLine3' => '',
        'dadAddressLine4' => 'Päevalille tn',
        'dadAddressLine5' => '13517 Tallinn',
        'dadAddressLine6' => '',
        'dadAddressLine7' => '',
    ],
    'behavior' => [
        'goodWithKids' => 'Yes',
        'goodWithDogs' => 'Yes',
        'goodWithcats' => 'No',
    ],
    'health' => [
        'allergies'         => 'Yes',
        'medicine'          => 'Yes',
        'neutered_spayed'   => 'No',
    ],
    'provider' => [
        'vet_name'          => 'Not disclosed',
        'vet_phone'         => 'Not disclosed',
        'vet_license_id'    => '123456',
        'vet_microchip'     => '123567',
        'rabies_id'         => 'Not disclosed',
    ],
];

$DATA[] = [
    'code' => 'AABBCC104',
    'petName' => 'Athena',
    'petImage' => 'https://petkeen.com/wp-content/uploads/2023/03/dog-breeds-shih-tzu_Liliya-Kulianionak_Shutterstock-760x542.jpg',
    'petBreed' => 'Husky',
    'petBio' => 'A friendly Husky girl.',
    'gender' => 'Boy',
    'age' => '5',
    'weight' => '20',
    'dadName' => 'Dad',
    'dadContact' => '+490123456789',
    'dadLocation' => 'https://www.google.com/maps/@50.9982818,10.6353859,12.6z?entry=ttu',
    'dadAddress' => [
        'dadAddressLine1' => 'EE',
        'dadAddressLine2' => '',
        'dadAddressLine3' => '',
        'dadAddressLine4' => 'Päevalille tn',
        'dadAddressLine5' => '13517 Tallinn',
        'dadAddressLine6' => '',
        'dadAddressLine7' => '',
    ],
    'behavior' => [
        'goodWithKids' => 'Yes',
        'goodWithDogs' => 'Yes',
        'goodWithcats' => 'No',
    ],
    'health' => [
        'allergies'         => 'Yes',
        'medicine'          => 'Yes',
        'neutered_spayed'   => 'No',
    ],
    'provider' => [
        'vet_name'          => 'Not disclosed',
        'vet_phone'         => 'Not disclosed',
        'vet_license_id'    => '123456',
        'vet_microchip'     => '123567',
        'rabies_id'         => 'Not disclosed',
    ],
];
